// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.Models;

#nullable disable

namespace PieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PieShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fruit pies"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cheese cakes"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Seasonal pies"
                        });
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/caramelpopcorncheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/caramelpopcorncheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "A rich, velvety cheesecake layered with golden caramel and finished with a generous topping of caramel popcorn for the perfect balance of smooth and crunchy.",
                            Name = "Caramel Popcorn Cheese Cake",
                            Price = 22.95m,
                            ShortDescription = "Silky cheesecake topped with caramel popcorn crunch."
                        },
                        new
                        {
                            PieId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/chocolatecheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/chocolatecheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Smooth dark chocolate cheesecake baked on a crunchy cookie crust and finished with chocolate curls. Rich, indulgent, and absolutely irresistible.",
                            Name = "Chocolate Cheese Cake",
                            Price = 19.95m,
                            ShortDescription = "Chocolate lover’s dream on a cookie crust."
                        },
                        new
                        {
                            PieId = 3,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/pistachecheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/pistachecheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "An elegant pistachio-infused cheesecake with a nutty aroma and a hint of vanilla, topped with crushed roasted pistachios for extra flavor and texture.",
                            Name = "Pistache Cheese Cake",
                            Price = 21.95m,
                            ShortDescription = "Creamy cheesecake with roasted pistachios."
                        },
                        new
                        {
                            PieId = 4,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/fruitpies/pecanpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/fruitpies/pecanpie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "A buttery, flaky crust filled with toasted pecans and a sweet caramelized filling. Crispy on top, gooey inside, and pure comfort with every slice.",
                            Name = "Pecan Pie",
                            Price = 21.95m,
                            ShortDescription = "Classic southern pie loaded with pecans."
                        },
                        new
                        {
                            PieId = 5,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/seasonal/birthdaypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/seasonal/birthdaypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Layers of vanilla custard and colorful sprinkles baked in a sweet pastry shell, topped with whipped cream — a perfect centerpiece for birthdays or any celebration.",
                            Name = "Birthday Pie",
                            Price = 29.95m,
                            ShortDescription = "Celebrate any day with sprinkles and joy."
                        },
                        new
                        {
                            PieId = 6,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Freshly sliced apples tossed in cinnamon sugar, baked in a golden flaky crust. A timeless favorite that tastes like home.",
                            Name = "Apple Pie",
                            Price = 12.95m,
                            ShortDescription = "Our bakery’s famous warm apple pie."
                        },
                        new
                        {
                            PieId = 7,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/blueberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/blueberrycheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "A smooth cheesecake base layered with a sweet blueberry compote. A balance of tangy and sweet that’s as beautiful as it is delicious.",
                            Name = "Blueberry Cheese Cake",
                            Price = 18.95m,
                            ShortDescription = "Creamy cheesecake topped with wild blueberries."
                        },
                        new
                        {
                            PieId = 8,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/cheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/cheesecake.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Rich, creamy, and timeless — our original cheesecake lets the smooth texture and subtle vanilla flavor shine through. Sometimes simple really is best.",
                            Name = "Cheese Cake",
                            Price = 18.95m,
                            ShortDescription = "Classic plain cheesecake, simple and pure."
                        },
                        new
                        {
                            PieId = 9,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "A juicy filling of ripe cherries wrapped in flaky pastry and baked until bubbling. Sweet, tangy, and the perfect balance of fruit and crust.",
                            Name = "Cherry Pie",
                            Price = 15.95m,
                            ShortDescription = "Sweet and tart cherries in a golden crust."
                        },
                        new
                        {
                            PieId = 10,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Apples baked with cinnamon, nutmeg, and cloves inside a buttery crust. A warm, cozy pie that smells like Christmas morning.",
                            Name = "Christmas Apple Pie",
                            Price = 13.95m,
                            ShortDescription = "Holiday spices meet our classic apple filling."
                        },
                        new
                        {
                            PieId = 11,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Bright red cranberries cooked down with sugar and citrus, baked in a flaky shell for a tart and festive flavor that’s perfect for winter.",
                            Name = "Cranberry Pie",
                            Price = 17.95m,
                            ShortDescription = "Tangy cranberries with a hint of orange zest."
                        },
                        new
                        {
                            PieId = 12,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg",
                            InStock = false,
                            IsPieOfTheWeek = false,
                            LongDescription = "Juicy, golden peaches nestled in a buttery crust and baked until tender and fragrant — a slice of summer all year long.",
                            Name = "Peach Pie",
                            Price = 15.95m,
                            ShortDescription = "Sun-ripened peaches baked to perfection."
                        },
                        new
                        {
                            PieId = 13,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Smooth pumpkin custard seasoned with cinnamon, nutmeg, and ginger, baked in a buttery crust. The ultimate autumn dessert.",
                            Name = "Pumpkin Pie",
                            Price = 12.95m,
                            ShortDescription = "A seasonal classic with warm spices."
                        },
                        new
                        {
                            PieId = 14,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Our rhubarb pie delivers that perfect tangy kick, balanced with just enough sweetness for a refreshingly bright dessert.",
                            Name = "Rhubarb Pie",
                            Price = 15.95m,
                            ShortDescription = "Sweet-tart rhubarb in a flaky homemade crust."
                        },
                        new
                        {
                            PieId = 15,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypie.jpg",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Bright strawberries layered in a buttery crust and covered in a light glaze. Simple, fresh, and bursting with natural flavor.",
                            Name = "Strawberry Pie",
                            Price = 15.95m,
                            ShortDescription = "Fresh strawberries, sweet glaze, perfect crust."
                        },
                        new
                        {
                            PieId = 16,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg",
                            InStock = false,
                            IsPieOfTheWeek = false,
                            LongDescription = "A smooth vanilla cheesecake topped with glossy strawberry sauce and slices of fresh fruit. Sweet, creamy, and absolutely delightful.",
                            Name = "Strawberry Cheese Cake",
                            Price = 18.95m,
                            ShortDescription = "Classic cheesecake with fresh strawberry topping."
                        });
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.HasOne("PieShop.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PieShop.Models.Category", b =>
                {
                    b.Navigation("Pies");
                });
#pragma warning restore 612, 618
        }
    }
}
